---
development:
  dialect: mysql
  database: test
  user: test
  password: test123
  host: 127.0.0.1
  port: 3306
  pool: 5

test:
  dialect: mysql
  database: test
  user: test
  password: test123
  host: 127.0.0.1
  port: 3306
  pool: 5

production:
  dialect: mysql
  database: test
  user: test
  password: test123
  host: 127.0.0.1
  port: 3306
  pool: 5
